spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: task-service
          uri: lb://task-service
          predicates:
            - Path=/api/v1/tasks/**
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/v1/users/**

server: 
  port: 8080